# Generated by Django 5.0.6 on 2024-05-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-date_added'], 'verbose_name': 'Events12', 'verbose_name_plural': 'Events'},
        ),
    ]
