# Generated by Django 5.0.6 on 2024-05-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_events_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-date_added'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
