# Generated by Django 5.0.6 on 2024-07-02 07:21

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_orgchart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.png', force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[500, 500], upload_to='faculties'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.png', force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[300, 300], upload_to='org_chart'),
        ),
    ]
