# Generated by Django 5.0.6 on 2024-06-02 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefactors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='benefactors')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('position', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Benefactor',
                'verbose_name_plural': 'Benefactors',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['date_added'],
            },
        ),
    ]
