# Generated by Django 5.0.6 on 2024-06-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefactors',
            options={'ordering': ['name'], 'verbose_name': 'Benefactor', 'verbose_name_plural': 'Benefactors'},
        ),
        migrations.RemoveField(
            model_name='benefactors',
            name='content',
        ),
        migrations.RemoveField(
            model_name='benefactors',
            name='date_added',
        ),
    ]
