# Generated by Django 5.0.6 on 2024-06-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_curriculum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Values',
        ),
    ]
