# Generated by Django 5.0.6 on 2024-06-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_delete_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactors',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='benefactors',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
