# Generated by Django 5.0.6 on 2024-05-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
