# Generated by Django 5.0.6 on 2024-05-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='content',
            field=models.TextField(),
        ),
    ]
