# Generated by Django 5.0.6 on 2024-05-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_testimonials_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdfs/'),
        ),
    ]
