# Generated by Django 5.0.6 on 2024-05-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_publications_title_alter_testimonials_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
