# Generated by Django 5.0.6 on 2024-06-10 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='officers')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Officer',
                'verbose_name_plural': 'Officers',
                'ordering': ['name'],
            },
        ),
    ]
