# Generated by Django 5.0.6 on 2024-07-02 07:21

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_alter_activities_name_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officers',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.png', force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[800, 800], upload_to='officers'),
        ),
    ]
