# Generated by Django 5.0.6 on 2024-06-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
