# Generated by Django 5.0.6 on 2024-05-31 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainings',
            options={'ordering': ['-date_added'], 'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
    ]
